/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Surfaces
        background:               '#111417',
        surface:                  '#111417',
        'surface-dim':            '#111417',
        'surface-bright':         '#37393d',
        'surface-container-lowest': '#0c0e12',
        'surface-container-low':  '#191c1f',
        'surface-container':      '#1d2023',
        'surface-container-high': '#282a2e',
        'surface-container-highest': '#323539',
        'surface-variant':        '#323539',
        // On-surfaces
        'on-background':          '#e1e2e7',
        'on-surface':             '#e1e2e7',
        'on-surface-variant':     '#c1c7d1',
        'inverse-surface':        '#e1e2e7',
        'inverse-on-surface':     '#2e3134',
        // Outlines
        outline:                  '#8b919a',
        'outline-variant':        '#41474f',
        // Primary
        primary:                  '#b3d5ff',
        'on-primary':             '#003256',
        'primary-container':      '#84bbf6',
        'on-primary-container':   '#004a7c',
        'primary-fixed':          '#d0e4ff',
        'primary-fixed-dim':      '#9ccaff',
        'on-primary-fixed':       '#001d35',
        'on-primary-fixed-variant': '#00497a',
        'inverse-primary':        '#226297',
        'surface-tint':           '#9ccaff',
        // Secondary
        secondary:                '#b4c8e2',
        'on-secondary':           '#1e3246',
        'secondary-container':    '#35485e',
        'on-secondary-container': '#a3b7d0',
        'secondary-fixed':        '#d0e4ff',
        'secondary-fixed-dim':    '#b4c8e2',
        'on-secondary-fixed':     '#071d30',
        'on-secondary-fixed-variant': '#35485e',
        // Tertiary (warm ochre)
        tertiary:                 '#ffca78',
        'on-tertiary':            '#432c00',
        'tertiary-container':     '#e6ad50',
        'on-tertiary-container':  '#624100',
        'tertiary-fixed':         '#ffddaf',
        'tertiary-fixed-dim':     '#f7bc5e',
        'on-tertiary-fixed':      '#281800',
        'on-tertiary-fixed-variant': '#614000',
        // Error
        error:                    '#ffb4ab',
        'on-error':               '#690005',
        'error-container':        '#93000a',
        'on-error-container':     '#ffdad6',
        // Brand specifics (interview room)
        'brand-surface-1':        '#13171C',
        'brand-surface-2':        '#1B2128',
        'brand-border':           '#2B333D',
        'brand-border-divider':   '#252C35',
        'brand-primary':          '#5B8CFF',
        'brand-primary-hover':    '#7BA3FF',
        'brand-text-primary':     '#F5F7FA',
        'brand-border-hover':     '#A8B0BB',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm:      '0.25rem',
        md:      '0.5rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        full:    '9999px',
      },
      spacing: {
        base: '4px',
        xs:   '8px',
        sm:   '12px',
        md:   '16px',
        lg:   '24px',
        xl:   '40px',
        'container-max': '1200px',
        gutter:          '24px',
      },
      fontFamily: {
        display:  ['Manrope', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg':  ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md':  ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1200px',
      },
    },
  },
  plugins: [],
}